name: Run Curl Every *** Minutes

on:
  schedule:
    - cron: '*/10 * * * *'  # 10分毎に実行

jobs:
  curl_job:
    runs-on: ubuntu-latest

    steps:
    - name: Execute Curl Command on Client
      run: curl -X GET https://ws-example-client.onrender.com/

    - name: Execute Curl Command on Server
      run: curl -X GET https://ws-example.onrender.com/
